### ISSUE TITLE
how to 

### ISSUE THREAD

**Issue by dianso** [l-Fingon-l/ReplayParser#1]

**Comment by dianso** [comment]
how to use it? help

**Comment by l-Fingon-l** [comment]
Hi!
Well, it depends on what you want to do with it.

In short: it's not really useful at this point as the parser was designed to handle the replays of 1.32.0-1.32.7 versions and the format has been slightly changed since.

It was originally designed to re-pack the replays between those versions (due to them being almost identical except for the checksums and the map paths). If you need to convert a replay of those versions, you might download the [last release](https://github.com/l-Fingon-l/ReplayParser/releases/tag/v1.0) of the software.

Otherwise, if you want to operate with the recent replays, I would suggest you take a look at the [renewed parser](https://github.com/l-Fingon-l/ReplayMap-Fixer). It does not export a clear API but there if you can read and edit the C++ code, there are a lot of useful functions in the `replay.cpp` file which you can incorporate into your project.

As for the clear and full API and a fully-featured library, the work on it is progress and I hope I will be able to release it as soon as possible.

If you still have any questions, please be sure to ask them.
With best regards.

**Comment by l-Fingon-l** [comment]
Hi!
Well, it depends on what you want to do with it.

In short: it's not really useful at this point as the parser was designed to handle the replays of 1.32.0-1.32.7 versions and the format has been slightly changed since.

It was originally designed to re-pack the replays between those versions (due to them being almost identical except for the checksums and the map paths). If you need to convert a replay of those versions, you might download the [last release](https://github.com/l-Fingon-l/ReplayParser/releases/tag/v1.0) of the software.

Otherwise, if you want to operate with the recent replays, I would suggest you take a look at the [renewed parser](https://github.com/l-Fingon-l/ReplayMap-Fixer). It does not export a clear API but there if you can read and edit the C++ code, there are a lot of useful functions in the `replay.cpp` file which you can incorporate into your project.

As for the clear and full API and a fully-featured library, the work on it is progress and I hope I will be able to release it as soon as possible.

If you still have any questions, please be sure to ask them.
With best regards.
